Repository CSC207-2022F-UofT/course-project-team-communify, pull requests merged in 2022-11, with the labels that each got.

#17 Suggestion: remove Factory design pattern where it does not make sense
  src/main/java/Entities/PlaylistFactory.java
  src/main/java/Entities/SongFactory.java
  src/main/java/Entities/SpaceFactory.java
Labels: invalid

#15 Completed input/output data, input/output boundary classes; example databases
  src/main/java/Database/artists.csv
  src/main/java/Database/playlists.csv
  src/main/java/Database/users.csv
  src/main/java/Entities/Playlist.java
  src/main/java/InputBoundary/recommendationInputBoundary.java
  src/main/java/InputData/playlistInputData.java
  src/main/java/OutputBoundary/recommendationOutputBoundary.java
  src/main/java/OutputData/songOutputData.java
Labels: enhancement

#16 base work + renaming
  src/main/java/Controller/spaceController.java
  src/main/java/InputBoundary/playSpaceInputBoundary.java
  src/main/java/InputBoundary/spaceAddInputBoundary.java
  src/main/java/InputBoundary/spaceInputBoundary.java
  src/main/java/OutputBoundary/spaceOutputBoundary.java
  src/main/java/OutputBoundary/spacePlayedOutputBoundary.java
  src/main/java/Presenter/spacePresenter.java
  src/main/java/UseCase/playSpace.java
  src/main/java/UseCase/playSpaceInteractor.java
Labels: enhancement

#20 playlistLibrary, userList, interfaces, and other bits and pieces
  build.gradle
  src/main/java/Database/artists.csv
  src/main/java/Database/playlistAccessInterface.java
  src/main/java/Database/playlistDsData.java
  src/main/java/Database/playlistLibrary.java
  src/main/java/Database/playlists.csv
  src/main/java/Database/songLibrary.java
  src/main/java/Database/userAccessInterface.java
  src/main/java/Database/userDsData.java
  src/main/java/Database/userList.java
  src/main/java/Database/users.csv
  src/main/java/Entities/Playlist.java
  src/main/java/Entities/RegularUser.java
  src/main/java/InputData/newPlaylistInputData.java
  src/main/java/UseCase/createPlaylist.java
  src/test/java/Database/PLibraryTest.java
Labels: enhancement

#27 Feature 6 search engine
  src/main/java/Controller/searchController.java
  src/main/java/InputBoundary/searchInputBoundary.java
  src/main/java/InputData/searchInputData.java
  src/main/java/OutputBoundary/searchOutputBoundary.java
  src/main/java/OutputData/searchOutputData.java
  src/main/java/Presenter/searchPresenter.java
  src/main/java/UseCase/Search.java
Labels: enhancement

#33 Updated audio engine
  src/main/java/Entities/JPlayer.java
  src/main/java/Entities/MusicPlayer.java
Labels: enhancement

#36 Updated: Feature 7 Audio System, playAudio + minor changes to other code
  src/main/java/Controller/playAudioController.java
  src/main/java/InputBoundary/playAudioInputBoundary.java
  src/main/java/InputData/audioInputData.java
  src/main/java/InputData/editPlaylistInputData.java
  src/main/java/InputData/newPlaylistInputData.java
  src/main/java/InputData/searchInputData.java
  src/main/java/InputData/songInputData.java
  src/main/java/UseCase/Search.java
  src/main/java/UseCase/editPlaylist.java
  src/main/java/UseCase/playAudioInteractor.java
  src/main/java/UseCase/playSong.java
Labels: enhancement

#39 space stuff
  src/main/java/Controller/spaceController.java
  src/main/java/Entities/Space.java
  src/main/java/InputBoundary/playSpaceInputBoundary.java
  src/main/java/InputBoundary/spaceAddInputBoundary.java
  src/main/java/InputData/songInputData.java
  src/main/java/InputData/spaceInputData.java
  src/main/java/Main.java
  src/main/java/OutputBoundary/spacePlayedOutputBoundary.java
  src/main/java/Presenter/spacePresenter.java
  src/main/java/UseCase/addSpace.java
  src/main/java/UseCase/playSpaceInteractor.java
  src/main/java/View/playlistView.java
  src/main/java/ViewModel/spaceViewModel.java
Labels: enhancement

#38 Unit testing for the audio engine and test song
  src/test/java/Entities/PlayerTest.java
  src/test/java/Entities/test.mp3
Labels: enhancement

#47 UPDATED Feature 7 - playSong() - needs to be tested, minor changes and additions to some of the skeletal files
  src/main/java/Controller/musicEngineController.java
  src/main/java/Controller/playAudioController.java
  src/main/java/Controller/playlistController.java
  src/main/java/Entities/Playlist.java
  src/main/java/InputBoundary/playAudioInputBoundary.java
  src/main/java/InputBoundary/playSongInputBoundary.java
  src/main/java/InputBoundary/shufflePlaylistInputBoundary.java
  src/main/java/InputBoundary/shuffleSongInputBoundary.java
  src/main/java/InputData/playlistInputData.java
  src/main/java/InputData/songInputData.java
  src/main/java/OutputData/songOutputData.java
  src/main/java/UseCase/playAudioInteractor.java
  src/main/java/UseCase/playPlaylist.java
  src/main/java/UseCase/playSong.java
  src/main/java/UseCase/playSongInteractor.java
  src/main/java/UseCase/playSpaceInteractor.java
  src/main/java/UseCase/shufflePlaylist.java
  src/test/java/UseCase/PPlaybackTest.java
Labels: enhancement

#48 Feature 9 listen to space
  src/main/java/Controller/musicEngineController.java
  src/main/java/Controller/spaceController.java
  src/main/java/InputBoundary/playSpaceInputBoundary.java
  src/main/java/InputBoundary/spaceAddInputBoundary.java
  src/main/java/InputData/playSpaceInputData.java
  src/main/java/OutputBoundary/spacePlayedOutputBoundary.java
  src/main/java/Presenter/songPresenter.java
  src/main/java/Presenter/spacePresenter.java
  src/main/java/UseCase/playSpaceInteractor.java
  src/main/java/View/playlistView.java
  src/main/java/ViewModel/musicEngineControllerViewModel.java
  src/main/java/ViewModel/spaceViewModel.java
  src/test/java/Entities/PlayerTest.java
Labels: enhancement

#63 Recommend song use case
  src/main/java/Controller/musicEngineController.java
  src/main/java/Database/songDsData.java
  src/main/java/InputBoundary/playSpaceInputBoundary.java
  src/main/java/InputBoundary/recommendationInputBoundary.java
  src/main/java/OutputBoundary/recommendationOutputBoundary.java
  src/main/java/Presenter/songPresenter.java
  src/main/java/UseCase/playSpaceInteractor.java
  src/main/java/UseCase/recommendSong.java
  src/main/java/ViewModel/musicEngineControllerViewModel.java
Labels: enhancement

#64 Completing the audio system use cases
  src/main/java/Controller/musicEngineController.java
  src/main/java/Controller/playAudioController.java
  src/main/java/Entities/MusicPlayer.java
  src/main/java/InputBoundary/NextSongInputBoundary.java
  src/main/java/InputBoundary/playAudioInputBoundary.java
  src/main/java/InputData/audioInputData.java
  src/main/java/InputData/playlistInputData.java
  src/main/java/InputData/songInputData.java
  src/main/java/Main.java
  src/main/java/UseCase/NextSong.java
  src/main/java/UseCase/pauseSong.java
  src/main/java/UseCase/playAudioInteractor.java
  src/main/java/ViewModel/musicEngineControllerViewModel.java
Labels: enhancement

#67 Views!
  src/main/java/View/artistView.java
  src/main/java/View/loginRegisterView.java
  src/main/java/View/playlistView.java
  src/main/java/View/searchOutputView.java
Labels: enhancement

#57 uploadSong Use Case, songLibrary fixes, split songAccessInterface into two separate Data Access Interfaces
  src/main/java/Controller/uploadSongController.java
  src/main/java/Database/GetSongAccessInterface.java
  src/main/java/Database/SaveSongAccessInterface.java
  src/main/java/Database/playlistDsData.java
  src/main/java/Database/songDsData.java
  src/main/java/Database/songLibrary.java
  src/main/java/Database/userDsData.java
  src/main/java/Entities/Song.java
  src/main/java/InputBoundary/uploadSongInputBoundary.java
  src/main/java/InputData/songInputData.java
  src/main/java/InputData/uploadSongInputData.java
  src/main/java/OutputBoundary/uploadSongOutputBoundary.java
  src/main/java/Presenter/uploadSongPresenter.java
  src/main/java/UseCase/Search.java
  src/main/java/UseCase/UploadSongInteractor.java
  src/main/java/UseCase/recommendSong.java
  src/main/java/UseCase/uploadSong.java
  src/main/java/ViewModel/uploadSongViewModel.java
  src/test/java/Database/SLibraryTest.java
  src/test/java/UseCase/UploadSongTest.java
Labels: enhancement

#68 Database SOLID Adherence
  src/main/java/Database/GetPlaylistAccessInterface.java
  src/main/java/Database/GetUserAccessInterface.java
  src/main/java/Database/LoginUserAccessInterface.java
  src/main/java/Database/SavePlaylistAccessInterface.java
  src/main/java/Database/SaveUserAccessInterface.java
  src/main/java/Database/playlistAccessInterface.java
  src/main/java/Database/playlistDsData.java
  src/main/java/Database/playlistLibrary.java
  src/main/java/Database/userAccessInterface.java
  src/main/java/Database/userList.java
  src/main/java/InputData/playlistInputData.java
  src/main/java/UseCase/CreatePlaylistInteractor.java
  src/test/java/Database/PLibraryTest.java
  src/test/java/Database/UListTest.java
Labels: refactor

#78 Playlist view, playbar, user login view
  src/main/java/Controller/LoginController.java
  src/main/java/Controller/musicEngineController.java
  src/main/java/Database/playlistDsData.java
  src/main/java/Database/playlists.csv
  src/main/java/Database/userList.java
  src/main/java/Database/users.csv
  src/main/java/Entities/MusicPlayer.java
  src/main/java/InputBoundary/NextSongInputBoundary.java
  src/main/java/InputBoundary/loginInputBoundary.java
  src/main/java/InputBoundary/pauseSongInputBoundary.java
  src/main/java/InputData/playlistInputData.java
  src/main/java/Main.java
  src/main/java/OutputBoundary/loginOutputBoundary.java
  src/main/java/OutputData/loginOutputData.java
  src/main/java/Presenter/userPresenter.java
  src/main/java/UseCase/Login.java
  src/main/java/UseCase/NextSong.java
  src/main/java/UseCase/RegisterInteractor.java
  src/main/java/UseCase/playPlaylist.java
  src/main/java/View/InMemoryPlaylist.java
  src/main/java/View/InMemorySong.java
  src/main/java/View/InMemoryUser.java
  src/main/java/View/PlayBar.java
  src/main/java/View/PlaylistPanelView.java
  src/main/java/View/loginRegisterView.java
  src/main/java/View/playlistView.java
  src/main/java/View/searchOutputView.java
  src/main/java/ViewModel/PlaylistDsView.java
  src/main/java/ViewModel/SongDsView.java
  src/main/java/ViewModel/UserDsView.java
  src/main/java/ViewModel/musicEngineControllerViewModel.java
  src/main/java/ViewModel/userViewModel.java
  src/test/java/UseCase/PPlaybackTest.java
Labels: bug, enhancement

#69 Added unit tests for my use cases, controller
  src/main/java/Controller/musicEngineController.java
  src/main/java/Entities/MusicPlayer.java
  src/main/java/UseCase/playPlaylist.java
  src/test/java/Controller/EngineTest.java
  src/test/java/UseCase/PPlaybackTest.java
  src/test/java/UseCase/PauseTest.java
  src/test/java/UseCase/PlayTest.java
  src/test/java/UseCase/RecommendTest.java
  src/test/java/UseCase/SkipTest.java
Labels: testing

#77 Feature 10 add to space
  src/main/java/Controller/musicEngineController.java
  src/main/java/InputBoundary/playSpaceInputBoundary.java
  src/main/java/InputData/playSpaceInputData.java
  src/main/java/InputData/playlistInputData.java
  src/main/java/OutputBoundary/SpacePlayedOutputBoundary.java
  src/main/java/Presenter/spacePresenter.java
  src/main/java/UseCase/Search.java
  src/main/java/UseCase/playSpaceInteractor.java
  src/main/java/View/playlistView.java
  src/main/java/View/searchOutputView.java
  src/main/java/ViewModel/musicEngineControllerViewModel.java
Labels: enhancement

#89 Fixed playlist view bug, added recommend button
  src/main/java/Controller/musicEngineController.java
  src/main/java/UseCase/playPlaylist.java
  src/main/java/View/PlayBar.java
  src/main/java/View/PlaylistPanelView.java
  src/main/java/View/playlistView.java
  src/main/java/View/searchOutputView.java
  src/main/java/ViewModel/musicEngineControllerViewModel.java
Labels: bug, enhancement

#95 Playlist bug fix
  src/main/java/Controller/musicEngineController.java
  src/main/java/InputBoundary/playPlaylistInputBoundary.java
  src/main/java/UseCase/NextSong.java
  src/main/java/UseCase/playPlaylist.java
  src/main/java/ViewModel/musicEngineControllerViewModel.java
Labels: bug
