Repository CSC207-2022F-UofT/course-project-team-communify, pull requests merged in 2022-12, with the labels that each got.

#107 The "I Swear I'm Not Going To Change View Anymore" Update + Tests
  src/main/java/Main.java
  src/main/java/controller/GetArtistSongController.java
  src/main/java/database/SongDsData.java
  src/main/java/database/artists.csv
  src/main/java/database/playlists.csv
  src/main/java/database/users.csv
  src/main/java/view/ArtistView.java
  src/main/java/view/DoubleIDButton.java
  src/main/java/view/LoginView.java
  src/main/java/view/PlaylistPanelView.java
  src/main/java/view/SearchOutputView.java
  src/main/java/view/assets/button/remove.png
  src/test/java/viewModel/ArtistViewModelTest.java
  src/test/java/viewModel/test.mp3
Labels: enhancement

#108 Adding remove songs action to the view
  src/main/java/presenter/UserPresenter.java
  src/main/java/useCase/EditPlaylistInteractor.java
  src/main/java/view/DoubleIDButton.java
  src/main/java/view/InMemoryUser.java
  src/main/java/view/LoginView.java
  src/main/java/view/NewPlaylistInputDataView.java
  src/main/java/view/PlaylistPanelView.java
  src/main/java/view/PlaylistView.java
  src/main/java/view/SearchOutputView.java
  src/main/java/view/assets/button/shuffle.png
  src/main/java/viewModel/SearchViewModel.java
  src/main/java/viewModel/UserDsView.java
  src/test/java/controller/MusicEngineControllerTest.java
  src/test/java/entities/PlaylistTest.java
  src/test/java/outputData/LoginInteractorOutputDataTest.java
  src/test/java/useCase/CreatePlaylistTest.java
  src/test/java/useCase/PlaySpaceTest.java
  src/test/java/viewModel/ArtistViewModelTest.java
Labels: bug, enhancement

#109 Shuffle I guess
  src/main/java/controller/MusicEngineController.java
  src/main/java/inputBoundary/PlayPlaylistInputBoundary.java
  src/main/java/inputBoundary/ShufflePlaylistInputBoundary.java
  src/main/java/inputData/PlaylistInputData.java
  src/main/java/outputBoundary/ShuffleOutputBoundary.java
  src/main/java/outputData/ShuffleOutputData.java
  src/main/java/useCase/PlayPlaylistInteractor.java
  src/main/java/useCase/ShufflePlaylistInteractor.java
  src/main/java/view/PlaylistPanelView.java
  src/main/java/viewModel/MusicEngineViewModel.java
  src/test/java/useCase/ShuffleTest.java
Labels: enhancement

#110 The Final Pull Request 🫡 (refactoring, tests, final changes)
  README.md
  src/main/java/Main.java
  src/main/java/database/PlaylistLibrary.java
  src/main/java/database/SaveSongAccessInterface.java
  src/main/java/database/SongDsData.java
  src/main/java/database/SongLibrary.java
  src/main/java/database/playlists.csv
  src/main/java/database/users.csv
  src/main/java/entities/JPlayer.java
  src/main/java/entities/MusicPlayer.java
  src/main/java/entities/Playlist.java
  src/main/java/inputData/PlaylistInputData.java
  src/main/java/inputData/SongInputData.java
  src/main/java/outputBoundary/NewPlaylistOutputBoundary.java
  src/main/java/outputData/SearchOutputData.java
  src/main/java/outputData/SongOutputData.java
  src/main/java/presenter/PlaylistPresenter.java
  src/main/java/presenter/SearchPresenter.java
  src/main/java/view/DoubleIDButton.java
  src/main/java/view/IDButton.java
  src/main/java/view/InMemoryPlaylist.java
  src/main/java/view/InMemorySong.java
  src/main/java/view/InMemoryUser.java
  src/main/java/view/NewPlaylistInputDataView.java
  src/main/java/view/NewPlaylistOutputDataView.java
  src/main/java/view/PlaylistPanelView.java
  src/main/java/view/PlaylistView.java
  src/main/java/view/SearchOutputView.java
  src/main/java/viewModel/PlaylistDsView.java
  src/main/java/viewModel/PlaylistViewModel.java
  src/main/java/viewModel/SearchViewModel.java
  src/main/java/viewModel/SongDsView.java
  src/test/java/controller/MusicEngineControllerTest.java
  src/test/java/database/PLibraryTest.java
  src/test/java/entities/PlayerTest.java
  src/test/java/entities/PlaylistTest.java
  src/test/java/useCase/CreatePlaylistTest.java
  src/test/java/useCase/EditPlaylistTest.java
  src/test/java/useCase/PPlaybackTest.java
  src/test/java/useCase/PauseTest.java
  src/test/java/useCase/PlaySpaceTest.java
  src/test/java/useCase/PlayTest.java
  src/test/java/useCase/SearchInteractorTest.java
  src/test/java/useCase/ShuffleTest.java
  src/test/java/useCase/SkipTest.java
  src/test/java/viewModel/ArtistViewModelTest.java
  src/test/java/viewModel/PlaylistViewModelTests.java
Labels: refactor
